const vscode = require("vscode");
const CSS = require("../css");
const css = new CSS({ console: vscode.window.showInformationMessage });
let cssTypeObj = {
  charset: 0,
  host: 1,
  import: 2,
  "font-face": 3,
  namespace: 4,
  page: 5,
  document: 6,
  comment: 7,
  mixin: 8,
  extend: 9,
  rule: 239,
  include: 240,
  "custom-media": 241,
  media: 242,
  supports: 243,
  keyframes: 244,
  keyframe: 245,
};
let ruleObj = {
  position: 10,
  top: 11,
  right: 12,
  bottom: 13,
  left: 14,
  "z-index": 15,
  display: 16,
  flex: 17,
  "flex-basis": 18,
  "flex-direction": 19,
  "flex-flow": 20,
  "flex-grow": 21,
  "flex-shrink": 22,
  "flex-wrap": 23,
  grid: 24,
  "grid-area": 25,
  "grid-auto-rows": 26,
  "grid-auto-columns": 27,
  "grid-auto-flow": 28,
  "grid-gap": 29,
  "grid-row": 30,
  "grid-row-start": 31,
  "grid-row-end": 32,
  "grid-row-gap": 33,
  "grid-column": 34,
  "grid-column-start": 35,
  "grid-column-end": 36,
  "grid-column-gap": 37,
  "grid-template": 38,
  "grid-template-areas": 39,
  "grid-template-rows": 40,
  "grid-template-columns": 41,
  gap: 42,
  "align-content": 43,
  "align-items": 44,
  "align-self": 45,
  "justify-content": 46,
  "justify-items": 47,
  "justify-self": 48,
  order: 49,
  float: 50,
  clear: 51,
  "box-sizing": 52,
  width: 53,
  "min-width": 54,
  "max-width": 55,
  height: 56,
  "min-height": 57,
  "max-height": 58,
  margin: 59,
  "margin-top": 60,
  "margin-right": 61,
  "margin-bottom": 62,
  "margin-left": 63,
  padding: 64,
  "padding-top": 65,
  "padding-right": 66,
  "padding-bottom": 67,
  "padding-left": 68,
  "object-fit": 69,
  "object-position": 70,
  overflow: 71,
  "overflow-x": 72,
  "overflow-y": 73,
  color: 74,
  font: 75,
  "font-weight": 76,
  "font-size": 77,
  "font-family": 78,
  "font-style": 79,
  "font-variant": 80,
  "font-size-adjust": 81,
  "font-stretch": 82,
  "font-effect": 83,
  "font-emphasize": 84,
  "font-emphasize-position": 85,
  "font-emphasize-style": 86,
  "font-smooth": 87,
  "line-height": 88,
  direction: 89,
  "letter-spacing": 90,
  "white-space": 91,
  "text-align": 92,
  "text-align-last": 93,
  "text-transform": 94,
  "text-decoration": 95,
  "text-emphasis": 96,
  "text-emphasis-color": 97,
  "text-emphasis-style": 98,
  "text-emphasis-position": 99,
  "text-indent": 100,
  "text-justify": 101,
  "text-outline": 102,
  "text-wrap": 103,
  "text-overflow": 104,
  "text-overflow-ellipsis": 105,
  "text-overflow-mode": 106,
  "text-orientation": 107,
  "text-shadow": 108,
  "vertical-align": 109,
  "word-wrap": 110,
  "word-break": 111,
  "word-spacing": 112,
  "overflow-wrap": 113,
  "tab-size": 114,
  hyphens: 115,
  "unicode-bidi": 116,
  columns: 117,
  "column-count": 118,
  "column-fill": 119,
  "column-gap": 120,
  "column-rule": 121,
  "column-rule-color": 122,
  "column-rule-style": 123,
  "column-rule-width": 124,
  "column-span": 125,
  "column-width": 126,
  "page-break-after": 127,
  "page-break-before": 128,
  "page-break-inside": 129,
  src: 130,
  "list-style": 131,
  "list-style-position": 132,
  "list-style-type": 133,
  "list-style-image": 134,
  "table-layout": 135,
  "empty-cells": 136,
  "caption-side": 137,
  background: 138,
  "background-color": 139,
  "background-image": 140,
  "background-repeat": 141,
  "background-position": 142,
  "background-position-x": 143,
  "background-position-y": 144,
  "background-size": 145,
  "background-clip": 146,
  "background-origin": 147,
  "background-attachment": 148,
  "background-blend-mode": 149,
  border: 150,
  "border-color": 151,
  "border-style": 152,
  "border-width": 153,
  "border-top": 154,
  "border-top-color": 155,
  "border-top-width": 156,
  "border-top-style": 157,
  "border-right": 158,
  "border-right-color": 159,
  "border-right-width": 160,
  "border-right-style": 161,
  "border-bottom": 162,
  "border-bottom-color": 163,
  "border-bottom-width": 164,
  "border-bottom-style": 165,
  "border-left": 166,
  "border-left-color": 167,
  "border-left-width": 168,
  "border-left-style": 169,
  "border-radius": 170,
  "border-top-left-radius": 171,
  "border-top-right-radius": 172,
  "border-bottom-right-radius": 173,
  "border-bottom-left-radius": 174,
  "border-image": 175,
  "border-image-source": 176,
  "border-image-slice": 177,
  "border-image-width": 178,
  "border-image-outset": 179,
  "border-image-repeat": 180,
  "border-collapse": 181,
  "border-spacing": 182,
  outline: 183,
  "outline-width": 184,
  "outline-style": 185,
  "outline-color": 186,
  "outline-offset": 187,
  "box-shadow": 188,
  "box-decoration-break": 189,
  transform: 190,
  "transform-origin": 191,
  "transform-style": 192,
  "backface-visibility": 193,
  perspective: 194,
  "perspective-origin": 195,
  visibility: 196,
  cursor: 197,
  opacity: 198,
  filter: 199,
  isolation: 200,
  "backdrop-filter": 201,
  "mix-blend-mode": 202,
  transition: 203,
  "transition-delay": 204,
  "transition-timing-function": 205,
  "transition-duration": 206,
  "transition-property": 207,
  animation: 208,
  "animation-name": 209,
  "animation-duration": 210,
  "animation-play-state": 211,
  "animation-timing-function": 212,
  "animation-delay": 213,
  "animation-iteration-count": 214,
  "animation-direction": 215,
  "animation-fill-mode": 216,
  appearance: 217,
  content: 218,
  clip: 219,
  "clip-path": 220,
  "counter-reset": 221,
  "counter-increment": 222,
  resize: 223,
  "user-select": 224,
  "nav-index": 225,
  "nav-up": 226,
  "nav-right": 227,
  "nav-down": 228,
  "nav-left": 229,
  "pointer-events": 230,
  quotes: 231,
  "touch-action": 232,
  "will-change": 233,
  zoom: 234,
  fill: 235,
  "fill-rule": 236,
  "clip-rule": 237,
  stroke: 238,
};
let reference = {
  rule: "declarations",
  media: "rules",
  mixin: "rules",
  document: "rules",
  keyframes: "keyframes",
  keyframe: "declarations",
  page: "declarations",
  "font-face": "declarations",
  host: "rules",
};
// 样式所占权重
function Weights(obj) {
  if (obj.type == "declaration") {
    let type = obj.prototype?.replace(/-(moz|webkit|ms|o)-/, "")||'';
    let val = ruleObj[type];
    val += obj.prototype?.includes("-o-") ? 0.1 : 0;
    val += obj.prototype?.includes("-ms-") ? 0.2 : 0;
    val += obj.prototype?.includes("-moz-") ? 0.3 : 0;
    val += obj.prototype?.includes("-webkit-") ? 0.4 : 0;
    return val;
  }
  return cssTypeObj[obj.type];
}
// 排序当前样式
function sorting(arr) {
  return arr.sort((pre, next) => {
    let preV = Weights(pre);
    let nextV = Weights(next);
    if (preV < nextV) {
      return -1;
    }
    if (preV > nextV) {
      return 1;
    }
    return 0;
  });
}
// 深层遍历排序
function deepVisit(obj) {
  let deepKey = reference[obj.type];
  if (deepKey) {
    obj[deepKey] = sorting(obj[deepKey]);
    obj[deepKey] = obj[deepKey].map(deepVisit);
  }
  return obj;
}

/**
 * css排序
 * @param {string} content 文档对象
 * @returns {string} 结果
 */
function cssSorting(content) {
  let ast = css.parse(content);
  let astRules = ast.stylesheet.rules;
  astRules = sorting(astRules);
  astRules = astRules.map(deepVisit);
  let str = css.stringify(ast);
  return str;
}
module.exports = cssSorting;
